spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    database: mysql
    hibernate:
      ddl-auto: none
server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-7714.cfapps.io/eureka/
  instance:
    hostname: movie-7714.cfapps.io
    nonSecurePort: 80
    preferIpAddress: false
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true